Align design of docker.yml to test.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -21,7 +21,7 @@ on:
 
   # Run after version tag is pushed
     tags:
-      - v[12]+.[0-9]+.[0-9]+
+      - v[0-9]+.[0-9]+.[0-9]+
 
 env:
   IMAGE_NAME: ${{ github.repository }}
@@ -30,11 +30,57 @@ jobs:
   build-and-push:
     runs-on: ubuntu-latest
 
+    outputs:
+      fullref: ${{ steps.getshortref.outputs.fullref }}
+      shortref: ${{ steps.getshortref.outputs.shortref }}
+      tagbuilt: ${{ steps.buildimage.outputs.tagbuilt }}
+      tagpushed: ${{ steps.pullimage.outputs.tagpushed }}
+
     steps:
       - uses: actions/checkout@v2
 
+      # Get the short reference name
+      - name: Get the short reference name
+        id: getshortref
+        run: |
+          _short_ref=
+          # If GITHUB_REF is a branch, use the branch name.
+          if [[ "${GITHUB_REF}" == "refs/heads/"* ]]; then
+            _short_ref=${GITHUB_REF#refs/heads/}
+            # If _short_ref is main, use latest instead.
+            if [ "${_short_ref}" = "main" ]; then
+              _short_ref=latest
+            fi
+          # If GITHUB_REF looks like a version, use the tag name
+          # after the leading v. So vX.Y.Z becomes X.Y.Z
+          elif [[ "${GITHUB_REF}" == "refs/tags/v"* ]]; then
+            _short_ref=${GITHUB_REF#refs/tags/v}
+          # If GITHUB_REF didn't match either of those rules, :scream:
+          else
+            echo "FAIL: Did not recognize GITHUB_REF '${GITHUB_REF}'."
+            exit 1
+          fi
+          echo "::set-output name=fullref::${GITHUB_REF}"
+          echo "::set-output name=shortref::${_short_ref}"
+
       - name: Build image
-        run: docker build . -t "${{ github.sha }}"
+        id: buildimage
+        run: |
+          _short_ref="${{ steps.getshortref.outputs.shortref }}"
+          _image_tag="ghcr.io/${IMAGE_NAME}:${_short_ref}"
+          if [ -r ./Dockerfile ]; then
+            echo "Found ./Dockerfile OK."
+          else
+            echo "FAIL: ./Dockerfile not readable."
+            exit 1
+          fi
+          if docker build . -q -t "${_image_tag}"; then
+            echo "Built '${_image_tag}' OK."
+          else
+            echo "FAIL: Failed to build '${_image_tag}'."
+            exit 1
+          fi
+          echo "::set-output name=tagbuilt::${_image_tag}"
 
       - name: Login to ghcr.io
         run: |
@@ -43,39 +89,13 @@ jobs:
           -u ${{ github.actor }} --password-stdin
 
       - name: Push image to ghcr.io
+        id: pushimage
         run: |
-          IMAGE_ID=ghcr.io/${IMAGE_NAME}
-
-          # Build image tag strings to push to GitHub's package registry.
-          _push_tags=""
-
-          # If GITHUB_REF is a branch, use the branch name.
-          if [[ "${GITHUB_REF}" == "refs/heads/"* ]]; then
-            VERSION=${GITHUB_REF#refs/heads/}
-            # If branchname is main, use latest instead.
-            if [ "${VERSION}" = "main" ]; then
-              VERSION=latest
-            fi
-            _push_tags+=" ${IMAGE_ID}:${VERSION}"
-
-          # If GITHUB_REF looks like a version tag, use the tag name
-          # after the leading v. So vX.Y.Z becomes X.Y.Z
-          # TODO: Decide when/where/how to push major tag
-          elif [[ "${GITHUB_REF}" == "refs/tags/v"* ]]; then
-            VERSION=${GITHUB_REF#refs/tags/v}
-            _push_tags+=" ${IMAGE_ID}:${VERSION}"
-
-          # If GITHUB_REF didn't match either of those rules, :scream:
+          _image_tag="${{ steps.buildimage.outputs.tagbuilt }}"
+          if docker push -q "${_image_tag}"; then
+            echo "Pushed '${_image_tag}' OK."
           else
-            echo "FAIL: Did not recognize GITHUB_REF '${GITHUB_REF}'."
+            echo "FAIL: Failed to push '${_image_tag}'."
             exit 1
           fi
-
-          echo IMAGE_ID=${IMAGE_ID}
-          echo VERSION=${VERSION}
-
-          for _this_tag in ${_push_tags}; do
-            echo "INFO: Tagging and pushing '${_this_tag}'."
-            docker tag "${{ github.sha }}" "${_this_tag}"
-            docker push "${_this_tag}"
-          done
+          echo "::set-output name=tagpushed::${_image_tag}"
