Move test into docker.yml
to avoid having to figure out how to transfer data between workflows.

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,8 +1,9 @@
-name: Build and push container
+name: Build, push, and test container
 
 # Use this workflow to:
-# - Manually build and push the Dockerfile
+# - Manually build and push from a branch
 # - Automatically build and push on certain changes
+# - Automatically test new/udpated deployments
 
 # TODO: Automate build and push for cutting a release
 
@@ -21,7 +22,7 @@ on:
       - octodns-requirements.txt
       - .github/workflows/docker.yml
 
-  # Run after version tag is pushed
+  # Run when a version tag is pushed
     tags:
       - v[0-9]+.[0-9]+.[0-9]+
 
@@ -103,3 +104,45 @@ jobs:
             exit 1
           fi
           echo "::set-output name=tagpushed::${_image_tag}"
+
+  test-published-action:
+    needs: build-and-push
+    env:
+      _tag_pushed="${{ jobs.build-and-push.outputs.tagpushed }}"
+      _short_ref="${{ jobs.build-and-push.outputs.shortref }}"
+    runs-on: ubuntu-latest
+
+    outputs:
+      actionat: ${{ steps.findaction.outputs.actionat }}
+      tagpulled: ${{ steps.pullimage.outputs.tagpulled }}
+
+    steps:
+      - uses: actions/checkout@v2
+
+      # TODO: Make this step :point_down: actually work
+      # Is the Action available at this reference?
+      - name: Verify Action is available
+        id: findaction
+        run: |
+          # _short_ref is set in this job's env
+          _short_ref="${{ steps.setshortref.outputs.shortref }}"
+          _actionat="${IMAGE_NAME}@${_short_ref}"
+          echo "::set-output name=actionat::${_actionat}"
+
+      # Is the Docker image publicly available at this reference?
+      - name: Verify Docker image is available
+        id: pullimage
+        run: |
+          # _tag_pushed is set in this job's env
+          docker logout "${_tag_pushed%%/*}"
+          if docker pull -q "${_tag_pushed}"; then
+            echo "Pulled '${_tag_pushed}' OK."
+          else
+            echo "FAIL: Failed to pull '${_tag_pushed}'."
+            exit 1
+          fi
+          echo "::set-output name=tagpulled::${_tag_pushed}"
+
+      # TODO: Make these steps :point_down: actually work
+      # Run the ghcr.io image with sample data
+      # Run the locally built image with sample data
