Can test.yml get output from job in docker.yml
when it's triggered by that other workflow?

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,8 +7,6 @@ name: Test the published Action
 
 # TODO: Make this workflow actually do :point_up: those things
 
-# TODO: Decide when/where/how to push major tag
-
 on:
   # Run when manually triggered
   workflow_dispatch:
@@ -27,7 +25,8 @@ jobs:
     runs-on: ubuntu-latest
 
     outputs:
-      shortref: ${{ steps.getshortref.outputs.shortref }}
+      fullref: ${{ steps.setshortref.outputs.fullref }}
+      shortref: ${{ steps.setshortref.outputs.shortref }}
       tagpulled: ${{ steps.pullimage.outputs.tagpulled }}
       tagbuilt: ${{ steps.buildimage.outputs.tagbuilt }}
       actionat: ${{ steps.findaction.outputs.actionat }}
@@ -35,27 +34,37 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       
-      # Get the short reference name
-      - name: Get the short reference name
-        id: getshortref
+      # Set the short and full reference names
+      - name: Set the short and full reference names
+        id: setshortref
         run: |
+          _full_ref=
           _short_ref=
-          # If GITHUB_REF is a branch, use the branch name.
-          if [[ "${GITHUB_REF}" == "refs/heads/"* ]]; then
-            _short_ref=${GITHUB_REF#refs/heads/}
-            # If _short_ref is main, use latest instead.
-            if [ "${_short_ref}" = "main" ]; then
-              _short_ref=latest
-            fi
-          # If GITHUB_REF looks like a version, use the tag name
-          # after the leading v. So vX.Y.Z becomes X.Y.Z
-          elif [[ "${GITHUB_REF}" == "refs/tags/v"* ]]; then
-            _short_ref=${GITHUB_REF#refs/tags/v}
-          # If GITHUB_REF didn't match either of those rules, :scream:
+          if [ "${GITHUB_EVENT_NAME}" = "workflow_run" ]; then
+            _full_ref="${{ jobs.build-and-push.outputs.fullref }}"
+            _short_ref="${{ jobs.build-and-push.outputs.shortref }}"
           else
-            echo "FAIL: Did not recognize GITHUB_REF '${GITHUB_REF}'."
-            exit 1
+            # If GITHUB_REF is a branch, use the branch name.
+            if [[ "${GITHUB_REF}" == "refs/heads/"* ]]; then
+              _short_ref=${GITHUB_REF#refs/heads/}
+
+              # If _short_ref is main, use latest instead.
+              if [ "${_short_ref}" = "main" ]; then
+                _short_ref=latest
+              fi
+            # If GITHUB_REF looks like a version, use the tag name
+            # after the leading v. So vX.Y.Z becomes X.Y.Z
+            elif [[ "${GITHUB_REF}" == "refs/tags/v"* ]]; then
+              _short_ref=${GITHUB_REF#refs/tags/v}
+            # If GITHUB_REF didn't match either of those rules, :scream:
+            else
+              echo "FAIL: Did not recognize GITHUB_REF '${GITHUB_REF}'."
+              exit 1
+            fi
           fi
+          echo "Set _full_ref to '${_full_ref}'."
+          echo "Set _short_ref to '${_short_ref}'."
+          echo "::set-output name=fullref::${_full_ref}"
           echo "::set-output name=shortref::${_short_ref}"
 
       # TODO: Make this step :point_down: actually work
@@ -64,7 +73,7 @@ jobs:
       - name: Verify Action is available
         id: findaction
         run: |
-          _short_ref="${{ steps.getshortref.outputs.shortref }}"
+          _short_ref="${{ steps.setshortref.outputs.shortref }}"
           _actionat="${IMAGE_NAME}@${_short_ref}"
           echo "::set-output name=actionat::${_actionat}"
 
@@ -72,7 +81,7 @@ jobs:
       - name: Verify Docker image is available
         id: pullimage
         run: |
-          _short_ref="${{ steps.getshortref.outputs.shortref }}"
+          _short_ref="${{ steps.setshortref.outputs.shortref }}"
           _image_tag="ghcr.io/${IMAGE_NAME}:${_short_ref}"
           if docker pull -q "${_image_tag}"; then
             echo "Pulled '${_image_tag}' OK."
